JUDGE_OEG_IT = """Score the response generated by a system to a user's request in {language} on a likert scale from 1 to 7. The quality levels associated with numerical scores are provided below:

7: The response fully adheres to all instructions that the user provided.
5: The chatbot mostly followed the instructions, conforming to the main points of the request but missing some details.
3: The chatbot followed only a small portion of the instructions or missed important points.
1: The chatbot entirely disregarded the instructions; the response appears to have no relation to the user’s request or is not in {language}.

Return only the score and nothing else.

Prompt: {input}
Response: {response}

Score (1-7):"""


JUDGE_OEG_NATURAL = """Score the response generated by a system to a user's request in {language} on a likert scale from 1 to 7. The quality levels associated with numerical scores are provided below:

7: The response represents fluent {language} text that might have been written by a native human speaker.
5: The response has some disfluencies that are noticeable but don’t significantly hinder understanding the response.
3: The response is highly disfluent. There are several grammatical errors. Most of the meaning can be determined, but only with conscious effort.
1: The response is incomprehensible or is not in {language}.

Return only the score and nothing else.

Prompt: {input}
Response: {response}

Score (1-7):"""


JUDGE_OEG_COHERENCE = """Score the response generated by a system to a user's request in {language} on a likert scale from 1 to 7. The quality levels associated with numerical scores are provided below:

7: The response is logically sound and appropriately structured with a clear sequence of nicely connected ideas and topics with no leaps in reasoning.
5: The response is generally well-structured and has a generally clear overall progression of ideas, but introduces a few logical gaps, or suddenly switches topics without an appropriate transition.
3: The response lacks an overall flow, and/or has multiple noticeable jumps between topics. It is possible to discern some relevant ideas, but the overall purpose of the response is incoherent.
1: The response has no overall structure, is in no way logically sound, and/or can be divided into many mostly-unrelated sections. It is difficult to identify any points the text is trying to make.

Return only the score and nothing else.

Prompt: {input}
Response: {response}

Score (1-7):"""

GEMBA_DA = """Score the following translation from {source_lang} to {target_lang} on a scale from 0 to 100, where a score of 0 means a broken or poor translation; 33 indicates a flawed translation with significant issues; 66 indicates a good translation with only minor issues in grammar, fluency, or consistency; and 100 represents a perfect translation in both meaning and grammar. Answer with only a whole number representing the score, and nothing else.

{source_lang} source text: 
{source_seg}
{target_lang} translation: 
{target_seg}
"""

JUDGE_SUM_FAITHFULNESS = """Score the summary generated by a system based on a set of reviews in {language} on a likert scale from 1 to 7. Evaluate whether all information in the summary can be traced back to the reviews. Treat the reviews as the source of truth and do not consider any external information. The quality levels associated with numerical scores are provided below:
7: All of the information in the summary is fully supported by the reviews and no meaning was changed.
5: Most information is supported, but a small part of the summary contains information that either contradicts or cannot be verified by the reviews.
3: More than half of the information in the summary either contradicts or cannot be verified by the reviews.
1: The summary is fully made up of information that either contradicts or cannot be verified by the reviews.
Return only the score and nothing else.

Reviews: {input}
Summary: {response}

Score (1-7):"""

JUDGE_SUM_COVERAGE = """Score the summary generated by a system based on a set of reviews in {language} on a likert scale from 1 to 7. Read the reviews and identify the most important points, then evaluate whether these key points are covered by the summary. The quality levels associated with numerical scores are provided below:
7: The summary covers all key points.
5: The summary covers about two thirds of the key points.
3: The summary covers about a third of the key points.
1: The summary does not cover any of the key points mentioned in the reviews.
Return only the score and nothing else.

Reviews: {input}
Summary: {response}

Score (1-7):"""

JUDGE_SUM_NATURALNESS = """Score the summary generated by a system based on a set of reviews in {language} on a likert scale from 1 to 7. Evaluate the degree to which the summary appears to be fluent, natural text in {language}, that is appropriate in terms of tone and formality. The quality levels associated with numerical scores are provided below:
7: The summary represents fluent {language} text that might have been written by a native human speaker.
5: The summary has some disfluencies that are noticeable but don't significantly hinder understanding the summary.
3: The summary is highly disfluent. There are several grammatical errors. Most of the meaning can be determined, but only with conscious effort. Alternatively, there are some words in a foreign language.
1: The summary is incomprehensible, or is not in {language}.
Return only the score and nothing else.

Reviews: {input}
Summary: {response}

Score (1-7):"""

JUDGE_SUM_COHERENCE = """Score the summary generated by a system based on a set of reviews in {language} on a likert scale from 1 to 7. Evaluate the degree to which the summary appears to be logically sound and internally consistent. The quality levels associated with numerical scores are provided below:
7: The summary is logically sound and appropriately structured with a clear sequence of nicely connected ideas and topics with no leaps in reasoning.
5: The summary is generally well-structured and has a generally clear overall progression of ideas, but introduces a few logical gaps, or suddenly switches topics without an appropriate transition.
3: The summary lacks an overall flow, and/or has multiple noticeable jumps between topics. It is possible to discern some relevant ideas, but the overall purpose of the summary is incoherent.
1: The summary has no overall structure, is in no way logically sound, and/or can be divided into many mostly-unrelated sections. It is difficult to identify any points the text is trying to make.
Return only the score and nothing else.

Reviews: {input}
Summary: {response}

Score (1-7):"""
